import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <img src="" alt="" />
        <a href="/">Home</a>
        <a href="/events">Events</a>
        <a href="/about-us">About Us</a>
      </header>

      <main className={styles.main}>
        <a href="">
          <img src="" alt="" />
          <h2>Event in Baku</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat
            blanditiis similique mollitia quasi quaerat distinctio voluptate
            quisquam nesciunt numquam ex.
          </p>
        </a>

        <a href="">
          <img src="" alt="" />
          <h2>Event in Khax</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat
            blanditiis similique mollitia quasi quaerat distinctio voluptate
            quisquam nesciunt numquam ex.
          </p>
        </a>
        
        <a href="">
          <img src="" alt="" />
          <h2>Event in Almali</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat
            blanditiis similique mollitia quasi quaerat distinctio voluptate
            quisquam nesciunt numquam ex.
          </p>
        </a>
      </main>

      <footer>
        <p>footer</p>
      </footer>
    </div>
  );
}
